const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const { config } = require('../../config/config');
const { logActivity } = require('../../lib/activityLog');

const BACKUP_DIR = path.resolve(__dirname, '../../../', config.backupDir);
// Filenames are always generated by this module (timestamp-based) — restore/delete/download
// only ever accept a name matching this pattern, which rules out path traversal.
const FILENAME_PATTERN = /^backup-\d{8}-\d{6}\.sql$/;
const MAX_BACKUPS = 14;

function ensureDir() {
  fs.mkdirSync(BACKUP_DIR, { recursive: true });
}

function timestampName() {
  const now = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  const date = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}`;
  const time = `${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
  return `backup-${date}-${time}.sql`;
}

// A configured tool path is either an actual file path (checkable with
// fs.existsSync) or a bare command name meant to be resolved from PATH
// (e.g. the "mysqldump"/"mysql" defaults on Linux/macOS) — existsSync would
// always report false for the latter even when the tool is installed and on
// PATH, so only pre-check paths that look like an actual path.
function isBareCommandName(p) {
  return path.basename(p) === p;
}

function assertToolAvailable(toolPath, envVarName, humanName) {
  if (isBareCommandName(toolPath)) return;
  if (!fs.existsSync(toolPath)) {
    const err = new Error(`ابزار ${humanName} یافت نشد (${toolPath}). مسیر آن را با متغیر محیطی ${envVarName} تنظیم کنید.`);
    err.status = 501;
    throw err;
  }
}

function assertValidFilename(filename) {
  if (!FILENAME_PATTERN.test(filename)) {
    const err = new Error('نام فایل پشتیبان نامعتبر است.');
    err.status = 400;
    throw err;
  }
}

async function createBackup(triggeredByUserId, { auto = false } = {}) {
  ensureDir();
  assertToolAvailable(config.mysqldumpPath, 'MYSQLDUMP_PATH', 'mysqldump');
  const filename = timestampName();
  const filePath = path.join(BACKUP_DIR, filename);
  const args = [
    '-h', config.db.host,
    '-P', String(config.db.port),
    '-u', config.db.user,
    ...(config.db.password ? [`--password=${config.db.password}`] : []),
    '--single-transaction',
    '--routines',
    config.db.database,
  ];

  await new Promise((resolve, reject) => {
    const out = fs.createWriteStream(filePath);
    const child = spawn(config.mysqldumpPath, args);
    child.stdout.pipe(out);
    let stderr = '';
    child.stderr.on('data', (chunk) => { stderr += chunk.toString(); });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code !== 0) {
        fs.unlink(filePath, () => {});
        return reject(new Error(stderr || `mysqldump با کد خطای ${code} خاتمه یافت.`));
      }
      resolve();
    });
  });

  await logActivity(null, triggeredByUserId, auto ? 'DB_BACKUP_AUTO' : 'DB_BACKUP_MANUAL', 'DatabaseBackup', filename, null);
  await rotateOldBackups();
  return listBackups().then((rows) => rows.find((r) => r.filename === filename));
}

async function rotateOldBackups() {
  const backups = await listBackups();
  const excess = backups.slice(MAX_BACKUPS);
  for (const backup of excess) {
    fs.unlink(path.join(BACKUP_DIR, backup.filename), () => {});
  }
}

async function listBackups() {
  ensureDir();
  const files = fs.readdirSync(BACKUP_DIR).filter((f) => FILENAME_PATTERN.test(f));
  const rows = files.map((filename) => {
    const stat = fs.statSync(path.join(BACKUP_DIR, filename));
    return { filename, sizeBytes: stat.size, createdAt: stat.mtime };
  });
  return rows.sort((a, b) => b.createdAt - a.createdAt);
}

function getBackupFilePath(filename) {
  assertValidFilename(filename);
  const filePath = path.join(BACKUP_DIR, filename);
  if (!fs.existsSync(filePath)) {
    const err = new Error('فایل پشتیبان یافت نشد.');
    err.status = 404;
    throw err;
  }
  return filePath;
}

async function deleteBackup(filename) {
  const filePath = getBackupFilePath(filename);
  fs.unlinkSync(filePath);
}

async function restoreBackup(filename, triggeredByUserId) {
  const filePath = getBackupFilePath(filename);
  assertToolAvailable(config.mysqlCliPath, 'MYSQL_CLI_PATH', 'mysql');
  const args = [
    '-h', config.db.host,
    '-P', String(config.db.port),
    '-u', config.db.user,
    ...(config.db.password ? [`--password=${config.db.password}`] : []),
    config.db.database,
  ];

  await new Promise((resolve, reject) => {
    const input = fs.createReadStream(filePath);
    const child = spawn(config.mysqlCliPath, args);
    input.pipe(child.stdin);
    let stderr = '';
    child.stderr.on('data', (chunk) => { stderr += chunk.toString(); });
    child.on('error', reject);
    child.on('close', (code) => {
      if (code !== 0) return reject(new Error(stderr || `mysql با کد خطای ${code} خاتمه یافت.`));
      resolve();
    });
  });

  await logActivity(null, triggeredByUserId, 'DB_RESTORE', 'DatabaseBackup', filename, null);
}

const AUTO_BACKUP_INTERVAL_MS = 24 * 60 * 60 * 1000;

// Polled once a minute from server.js (matches the broadcast/report poll pattern)
// — only actually runs mysqldump once the newest backup is >= 24h old.
async function runScheduledBackupIfDue() {
  const backups = await listBackups();
  const newest = backups[0];
  if (newest && Date.now() - new Date(newest.createdAt).getTime() < AUTO_BACKUP_INTERVAL_MS) {
    return;
  }
  await createBackup(null, { auto: true });
}

module.exports = {
  createBackup,
  listBackups,
  getBackupFilePath,
  deleteBackup,
  restoreBackup,
  assertValidFilename,
  runScheduledBackupIfDue,
};
